package CorbaApp;


/**
* CorbaApp/Center.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Hirangi/git/DistributedSchoolManagementSystem-Corba/src/Center.idl
* Friday, 7 July, 2017 3:32:28 PM EDT
*/

public interface Center extends CenterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Center
