package CorbaApp;


/**
* CorbaApp/CenterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Hirangi/git/DistributedSchoolManagementSystem-Corba/src/Center.idl
* Friday, 7 July, 2017 3:32:28 PM EDT
*/

public interface CenterOperations 
{
  String sayHello ();
  String createTRecord (String managerID, String fname, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String fname, String lastName, String courseRegistered, String status, String statusDate);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  void shutdown ();
} // interface CenterOperations
