package CorbaApp;

/**
* CorbaApp/CenterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Hirangi/git/DistributedSchoolManagementSystem-Corba/src/Center.idl
* Friday, 7 July, 2017 3:32:28 PM EDT
*/

public final class CenterHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaApp.Center value = null;

  public CenterHolder ()
  {
  }

  public CenterHolder (CorbaApp.Center initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaApp.CenterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaApp.CenterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaApp.CenterHelper.type ();
  }

}
