package CorbaApp;


/**
* CorbaApp/Center.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Monday, 10 July, 2017 9:31:37 AM EDT
*/

public interface Center extends CenterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Center
