package CorbaApp;


/**
* CorbaApp/CenterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Monday, 10 July, 2017 9:31:37 AM EDT
*/

public interface CenterOperations 
{
  String createTRecord (String managerID, String fname, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String fname, String lastName, String courseRegistered, String status, String statusDate);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
  void shutdown ();
} // interface CenterOperations
