package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, 7 July, 2017 12:17:11 PM EDT
*/

public interface HelloOperations 
{
  String sayHello ();
  String createTRecord (String managerID, String fname, String lastName, String address, String phone, String specialization, String location);
  void shutdown ();
} // interface HelloOperations
