package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, 7 July, 2017 12:09:18 PM EDT
*/

public interface HelloOperations 
{
  String sayHello ();
  String createTRecord (String fname);
  void shutdown ();
} // interface HelloOperations
